const percorsi = {
  "Cerchie e Circonvallazioni": [
    {
      "nomePercorso": "CERCHIA DEI NAVIGLI",
      "tappe": [
        "Piazza Cavour",
        "Via Fatebenefratelli",
        "Piazza San Marco",
        "Via Pontaccio",
        "Via Tivoli",
        "Largo Greppi",
        "Foro Bonaparte (Pari)",
        "Largo Cairoli",
        "Foro Bonaparte (Dispari)",
        "Piazzale Cardorna",
        "Via Carducci",
        "Largo D'Ancona",
        "Via Carducci",
        "Via De Amicis",
        "Piazza Resistenza Partigiana",
        "Via De Amicis",
        "Via Molino delle Armi",
        "Via Santa Sofia",
        "Via Francesco Sforza",
        "Via Visconti Di Modrone",
        "Via San Damiano",
        "Via Senato",
        "Piazza Cavour"
      ]
    },
    {
      "nomePercorso": "BASTIONI",
      "tappe": [
        "Piazza della Repubblica",
        "Via Monte Santo",
        "Piazza Principessa Clotilde",
        "Bastioni di Porta Nuova",
        "Piazza 25 Aprile",
        "Via Crispi",
        "Piazzale Baiamonti",
        "Bastioni di Porta Volta",
        "Piazzale Biancamano",
        "Piazzale Lega Lombarda",
        "Viale Elvezia",
        "Via Douhet",
        "Via Melzi D'Eril",
        "Via Canova",
        "Viale Milton",
        "Viale Moeliere",
        "Via Curie",
        "Viale 20 Settembre",
        "Piazza Conciliazione",
        "Via Toti",
        "Piazzale Baracca",
        "Corso di Porta Vercellina",
        "Piazzale Aquileia",
        "Viale Papiniano",
        "Piazza Sant'Agostino",
        "Viale Papiniano",
        "Piazza Cantore",
        "Viale G. D'Annunzio",
        "Piazzale 24 Maggio",
        "Viale Gian Galeazzo",
        "Piazzale di Porta Lodovica",
        "Viale Beatrice D'Este",
        "Largo Isabella D'Aragona",
        "Viale Beatrice D'Este",
        "Viale Filippetti",
        "Piazza Medaglie D'Oro",
        "Viale Caldara",
        "Viale Regina Margherita",
        "Piazza Cinque Giornate",
        "Viale Bianca Maria",
        "Piazza Tricolore",
        "Viale Majno",
        "Piazzale Oberdan",
        "Bastioni di Porta Venezia",
        "Via Città di Fiume",
        "Piazza della Repubblica"
      ]
    },
    {
      "nomePercorso": "CIRCONVALLAZIONE TRANVIARIA",
      "tappe": [
        "Piazza della Repubblica",
        "Via Monte Santo",
        "Piazza Principessa Clotilde",
        "Viale Monte Grappa",
        "Piazza 25 Aprile",
        "Via Pasubio",
        "Piazzale Baiamonti",
        "Via Ceresio",
        "Piazzale Cimitero Monumentale",
        "Via Procaccini",
        "Piazza Gramsci",
        "Via Procaccini",
        "Corso Sempione",
        "Via Canova",
        "Via Mario Pagano",
        "Largo 5° Alpini",
        "Via Ariosto",
        "Piazza Conciliazione",
        "Via Ariosto",
        "Piazzale Baracca",
        "Via San Michele del Carso",
        "Piazza De Meis",
        "Via San Michele del Carso",
        "Piazzale Aquileia",
        "Viale Coni Zugna",
        "Viale Gorizia",
        "Piazzale 24 Maggio",
        "Via Col di Lana",
        "Piazzale di Porta Lodovica",
        "Viale Bligni",
        "Viale Sabotino",
        "Piazza Medaglie D'Oro",
        "Viale Montenero",
        "Piazza 5 Giornate",
        "Viale Premuda",
        "Piazza Tricolore",
        "Viale Piave",
        "Piazzale Oberdan",
        "Viale Vittorio Veneto",
        "Piazza della Repubblica"
      ]
    },
    {
      "nomePercorso": "CIRCONVALLAZIONE ESTERNA FILOTRANVIARIA",
      "tappe": [
        "Piazzale Loreto",
        "Viale Abruzzi",
        "Piazza Ascoli",
        "Viale dei Mille",
        "Piazza Dateo",
        "Viale Piceno",
        "Piazza Emilia",
        "Viale Umbria",
        "Piazza Cappelli",
        "Viale Umbria",
        "Piazzale Lodi",
        "Viale Isonzo",
        "Piazza Trento",
        "Viale Isonzo",
        "Viale Toscana",
        "Largo Beethoven",
        "Viale Toscana",
        "Viale Tibaldi",
        "Piazza Bibbiena",
        "Viale Tibaldi",
        "Viale Liguria",
        "Piazza Belfanti",
        "Viale Liguria",
        "Largo Ascari",
        "Viale Cassala",
        "Cavalcavia delle Milizie",
        "Viale Troja",
        "Piazza Napoli",
        "Viale Misurata",
        "Piazza Bolivar",
        "Viale Misurata",
        "Piazza Tripoli",
        "Viale Bezzi",
        "Piazza Ghirlandaio",
        "Viale Ranzoni",
        "Piazzale Brescia",
        "Viale Murillo",
        "Piazzale Zavattari",
        "Viale Migliara",
        "Piazzale Lotto",
        "Viale Elia",
        "Piazzale Stuparich",
        "Viale Serra",
        "Viale Monte Ceneri",
        "Cavalcavia Bacula",
        "Piazzale Lugano",
        "Viale Bodio",
        "Piazza Nigra",
        "Viale Jenner",
        "Piazzale Maciacchini",
        "Viale Marche",
        "Piazza Carbonari",
        "Viale Lunigiana",
        "Viale Brianza",
        "Piazzale Loreto"
      ]
    },
    {
      "nomePercorso": "CIRCONVALLAZIONE ESTERNA",
      "tappe": [
        "Piazzale Durante",
        "Viale Lombardia",
        "Piazzale Piola",
        "Viale Romagna",
        "Largo Rio de Janeiro",
        "Viale Romagna",
        "Piazzale Ferravilla",
        "Viale Romagna",
        "Piazzale Susa",
        "Viale Campania",
        "Viale Mugello",
        "Viale Molise",
        "Piazzale Cuoco",
        "Viale Puglie",
        "Piazza Bologna",
        "Viale Lucania",
        "Piazzale Corvetto",
        "Viale Polesine",
        "Piazzale Ferrara",
        "Via Comacchio",
        "Piazza Angilberto Secondo",
        "Via Marco D'Agrate",
        "Via Quaranta",
        "Via Solaroli",
        "Piazza Chiaradia",
        "Via Antonini",
        "Viale Giovanni Da Cermenate",
        "Sotto troviamo Piazza Carrara",
        "Via/Cavalcavia Schiavoni",
        "Passiamo sotto Piazza Maggi",
        "Viale Famagosta",
        "Piazza Miani",
        "Via Santa Rita Da Cascia",
        "Largo Giò Ponti",
        "Via Santa Rita Da Cascia",
        "Piazza Omm",
        "Cavalcavia Don Milani",
        "Via Brunelleschi",
        "Via Bellini",
        "Piazza Frattini",
        "Via Bartolomeo D'Alviano",
        "Piazzale Giovanni dalle Bande Nere",
        "Via Pisa",
        "Piazzale Siena",
        "Viale Aretusa",
        "Piazzale Selinunte",
        "Via Jonio",
        "Piazzale Segesta",
        "Via Gavirate",
        "Largo Gavirate",
        "Via Gignese",
        "Via Caprilli",
        "Piazzale Lotto"
      ]
    }
],
  "PERCORSI PARTENZA DUOMO": [
    {
  "nomePercorso": "DUOMO > MALPENSA",
  "tappe": [
    "Via Mengoni",
    "Largo Abbado",
    "Via San Protaso",
    "Largo Belotti",
    "Via Porrone",
    "Via Broletto",
    "Via Cusani",
    "Largo Cairoli",
    "Foro Bonaparte (Dispari)",
    "Piazzale Cadorna",
    "Via Paleocapa",
    "Via Alemagna",
    "Via Moeliere",
    "Viale Milton",
    "Via Canova",
    "Corso Sempione",
    "Piazza Firenze",
    "Viale Certosa",
    "Piazzale Accursio",
    "Viale Certosa",
    "Piazza Ai Laghi",
    "Via Montefeltro",
    "Cavalcavia deil Ghisallo",
    "Uscite a Destra: A4 direzione Venezia",
    "Via Cogne che ci porta verso Ospedale Sacco, Statale Varesina",
    "Uscite a Sinistra: A4 Milano Torino",
    "Proseguiamo dritto",
    "Arriviamo all'uscita Nuovo Polo Fieristico Roh Pero, Milano Meda, Monza Bollate, Tangenziale Nord",
    "Proseguiamo dritto e arriviamo alla Barriera Nord",
    "Uscite: Arese Lainate, Bivio A8 Varese > Gravellona Toce, Bivio A9 Como > Chiasso",
    "Proseguiamo sulla A8 trovando le uscite: Origgio Ovest, Legnano Rescaldina, Castellanza, Busto Arsizio",
    "Usciamo a Busto Arsizio",
    "Strada Statale 336 per Malpensa, Terminal 2, Terminal 1"
  ]
},
{
  "nomePercorso": "DUOMO > CENTRALE",
  "tappe": [
    "Via Mengoni",
    "Largo Abbado",
    "Via Santa Margherita",
    "Piazza della Scala",
    "Via Manzoni",
    "Piazza Cavour",
    "Via Turati",
    "Largo Donegani",
    "Piazza Stati Uniti D'America",
    "Via Turati",
    "Piazza della Repubblica",
    "Via Vittor Pisani",
    "Piazza Duca D'Aosta"
  ]
},
{
  "nomePercorso": "DUOMO > LINATE",
  "tappe": [
    "Piazza Duomo",
    "Via Mengoni",
    "Largo Abbado",
    "Via San Protaso",
    "Largo Belotti",
    "Via Porrone",
    "Via San Prospero",
    "Via Dante",
    "Piazza Cordusio",
    "Via Orefici",
    "Piazza Duomo",
    "Via Mazzini",
    "Largo Borges",
    "Via Mazzini",
    "Piazza Missori",
    "Via Albricci",
    "Via Larga",
    "Piazza Fontana",
    "Via del Verziere",
    "Largo Bersaglieri di Italia",
    "Via del Verziere",
    "Largo Augusto",
    "Corso Di porta Vittoria",
    "Piazza 5 Giornate",
    "Corso 22 Marzo",
    "Piazza Santa Maria del Suffragio",
    "Corso 22 Marzo",
    "Piazza Emilia",
    "Corso 22 Marzo",
    "Piazza Grandi",
    "Corso 22 Marzo",
    "Viale Corsica",
    "Largo Rodari",
    "Viale Corsica",
    "Tre Ponti",
    "Viale Forlanini"
  ]
},
{
  "nomePercorso": "DUOMO > CITY LIFE",
  "tappe": [
    "Via Mengoni",
    "Largo Abbado",
    "Via San Protaso",
    "Largo Belotti",
    "Via Porrone",
    "Via San Prospero",
    "Via Meravigli",
    "Largo Santi Pietro e Lino",
    "Via Meravigli",
    "Corso Magenta",
    "Largo Enzo Tortora",
    "Corso Magenta",
    "Largo D'Ancona",
    "Via Vincenzo Monti",
    "Piazza Virgilio",
    "Via Vincenzo Monti",
    "Largo Quinto Alpini",
    "Via Vincenzo Monti",
    "Piazza Giovanni XXIII",
    "Via Vincenzo Monti",
    "Piazza 6 Febbraio"
  ]
},
],
  "PERCORSI PARTENZA STAZIONE CENTRALE": [
    {
  "nomePercorso": "CENTRALE > DUOMO",
  "tappe": [
    "Via Vittor Pisani",
    "Piazza della Repubblica",
    "Via Turati",
    "Piazza Stati Uniti D'America",
    "Largo Donegani",
    "Via Turati",
    "Piazza Cavour",
    "Via Manzoni",
    "Piazza della Scala",
    "Via Santa Margherita",
    "Via San Protaso",
    "Largo Belotti",
    "Via Porrone",
    "Via San Prospero",
    "Via Dante",
    "Piazza Cordusio",
    "Via Orefici",
    "Piazza Duomo"
  ]
},
{
  "nomePercorso": "CENTRALE > LINATE",
  "tappe": [
    "Via Vitruvio",
    "Piazza Lima",
    "Via Plinio",
    "Viale Abruzzi",
    "Piazza Ascoli",
    "Viale dei Mille",
    "Via Gaio",
    "Piazza Novelli",
    "Via Sidoli",
    "Via Gozzi",
    "Piazza Susa",
    "Viale Argonne",
    "Via Dell'Ongaro",
    "Piazza Adigrat",
    "Via Battistotti Sassi",
    "Viale Corsica",
    "Largo Rodari",
    "Viale Corsica",
    "Tre Ponti",
    "Viale Forlanini"
  ]
},
{
  "nomePercorso": "CENTRALE > CITY LIFE",
  "tappe": [
    "Via Pirelli",
    "Piazza Einaudi",
    "Via Melchiorre Gioia",
    "Via Don Sturzo",
    "Via Del Nord",
    "Via Don Sturzo",
    "Via Ferrari",
    "Piazzale Cimitero Monumentale",
    "Via Procaccini",
    "Piazza Gramsci",
    "Via Procaccini",
    "Via Ferrucci",
    "Via Ippolito Nievo",
    "Via Vincenzo Monti",
    "Piazza 6 Febbraio"
  ]
}
  ],
    "PERCORSI PARTENZA LINATE": [
      {
  "nomePercorso": "LINATE > DUOMO",
  "tappe": [
    "Viale Forlanini",
    "Tre Ponti",
    "Viale Corsica",
    "Largo Rodari",
    "Viale Corsica",
    "Corso 22 Marzo",
    "Piazza Grandi",
    "Corso 22 Marzo",
    "Piazza Emilia",
    "Corso 22 Marzo",
    "Piazza Santa Maria del Suffragio",
    "Corso 22 Marzo",
    "Piazza 5 Giornate",
    "Corso di Porta Vittoria",
    "Largo Marco Biagi",
    "Piazza San Pietro in Gessate",
    "Via Cesare Battisti",
    "Largo Augusto",
    "Via Cavallotti",
    "Corso Europa",
    "Largo Bersaglieri di'Italia",
    "Via del Verziere",
    "Piazza Fontana",
    "Via Larga",
    "Via Baracchini",
    "Piazza Diaz",
    "Via Giardino",
    "Largo Borges",
    "Via Mazzini",
    "Piazza Duomo"
  ]
},
{
  "nomePercorso": "LINATE > STAZIONE CENTRALE",
  "tappe": [
    "Viale Forlanini",
    "Tre Ponti",
    "Viale Corsica",
    "Largo Rodari",
    "Via Cardinal Mezzofanti",
    "Largo Sereni",
    "Via Pannonia",
    "Viale Argonne",
    "Piazza Fusina",
    "Viale Argonne",
    "Piazzale Susa",
    "Via Sidoli",
    "Piazza Novelli",
    "Via Gaio",
    "Viale Dei Mille",
    "Piazza Ascoli",
    "Viale Abruzzi",
    "Via Plinio",
    "Piazza Lima",
    "Via Vitruvio",
    "Piazza Duca D'Aosta"
  ]
},
{
  "nomePercorso": "LINATE > CITY LIFE",
  "tappe": [
    "Viale Forlanini",
    "Tre Ponti",
    "Viale Corsica",
    "Largo Rodari",
    "Viale Corsica",
    "Corso 22 Marzo",
    "Piazza Grandi",
    "Corso 22 Marzo",
    "Piazza Emilia",
    "Corso 22 Marzo",
    "Piazza Santa Maria del Suffragio",
    "Corso 22 Marzo",
    "Piazza 5 Giornate",
    "Corso di Porta Vittoria",
    "Largo Marco Biagi",
    "Piazza San Pietro in Gessate",
    "Via Cesare Battisti",
    "Largo Augusto",
    "Via Cavallotti",
    "Corso Europa",
    "Largo Bersaglieri di Italia",
    "Via del Verziere",
    "Piazza Fontata",
    "Via Larga",
    "Via Baracchini",
    "Piazza Diaz",
    "Via Giardino",
    "Via Falcone",
    "Via Unione",
    "Piazza Santa Maria Beltrade",
    "Via Torino",
    "Via San Maurilio",
    "Piazza Bonomelli",
    "Via Sant'Orsola",
    "Via Cappuccio",
    "Via Luini",
    "Corso Magenta",
    "Largo Enzo Tortora",
    "Corso Magenta",
    "Largo D'Ancona",
    "Via Vincenzo Monti",
    "Piazza Virgilio",
    "Via Vincenzo Monti",
    "Largo 5° Alpini",
    "Via Vincenzo Monti",
    "Piazza Giovanni XXIII",
    "Via Vincenzo Monti",
    "Piazza 6 Febbraio"
  ]
}
    ],
    "PERCORSI PARTENZA CITY LIFE": [
{
  "nomePercorso": "CITY LIFE > LINATE",
  "tappe": [
    "Piazza 6 Febbraio",
    "Via Boezio",
    "Largo Domodossola",
    "Via Domodossola",
    "Via Poliziano",
    "Piazza Gerusalemme",
    "Via Fratelli Induno",
    "Via Cenisio",
    "Largo Pian del Re",
    "Via Cenisio",
    "Piazza Coriolano",
    "Via Luigi Nono",
    "Piazza Cimitero Monumentale",
    "Via Ferrari",
    "Via Don Sturzo",
    "Via del Nord",
    "Via Don Sturzo",
    "Via Della Liberazione",
    "Piazza San Gioacchimo",
    "Via Cartesio",
    "Piazza della Repubblica",
    "Via Franchetti",
    "Via Finocchiaro Aprile",
    "Viale Tunisia",
    "Largo Bellintani",
    "Viale Tunisia",
    "Viale Regina Giovanna",
    "Piazza Santa Francesca Romana",
    "Viale Regina Giovanna",
    "Piazza 8 Novembre",
    "Viale Regina Giovanna",
    "Piazza Adelaide di Savoia",
    "Viale Giustiniano",
    "Via Gaio",
    "Piazza Novelli",
    "Via Sidoli",
    "Via Gozzi",
    "Piazzale Susa",
    "Viale Argonne",
    "Via Dell'Ongaro",
    "Piazza Adigrat",
    "Via Battistotti Sassi",
    "Viale Corsica",
    "Largo Rodari",
    "Viale Corsica",
    "Tre Ponti",
    "Viale Forlanini"
  ]
}
],
    "PERCORSI PARTENZA SAN BABILA": [
{
  "nomePercorso": "SAN BABILA > ORIO AL SERIO",
  "tappe": [
    "Corso Venezia",
    "Piazza Oberdan",
    "Corso Buenos Aires",
    "Piazza Lima",
    "Corso Buenos Aires",
    "Piazza Argentina",
    "Corso Buenos Aires",
    "Piazzale Loreto",
    "Via Andrea Costa",
    "Piazza Durante",
    "Via Leoncavallo",
    "Piazza Sire Raul",
    "Viale Palmanova",
    "Tangenziale direzione Agrate",
    "USCITE: Bretella per tangenziale Nord, Cologno Ovest, Cologno Est, Cernusco/Brugherio, Carugate, Barriera di Agrate",
    "A Sinistra Troviamo Lecco e Usmate Velate",
    "Poi Bivio per A4 Direzione Torino/Venezia",
    "Prendiamo A4 direzione Venezia",
    "USCITE: Agrate, TEM (Tangenziale Esterna Milanese), Cavenago/Cambiago, Trezzo sull'Adda, Capriate San Gervaso, Dalmine, Bergamo",
    "Usciamo a Bergamo",
    "Prendiamo direzione Orio Aereoporto"
  ]
}
],
    "PERCORSI PARTENZA PIAZZA DELLA SCALA": [
{
  "nomePercorso": "PIAZZA DELLA SCALA > ORIO AL SERIO",
  "tappe": [
    "Via Manzoni",
    "Piazza Cavour",
    "Via Palestro",
    "Corso Venezia",
    "Piazza Oberdan",
    "Corso Buenos Aires",
    "Piazza Lima",
    "Corso Buenos Aires",
    "Piazza Argentina",
    "Corso Buenos Aires",
    "Piazzale Loreto",
    "Via Andrea Costa",
    "Piazza Durante",
    "Via Leoncavallo",
    "Piazza Sire Raul",
    "Viale Palmanova",
    "Tangenziale direzione Agrate"
  ],
  "note": [
    "USCITE: Bretella per tangenziale Nord, Cologno Ovest, Cologno Est, Cernusco/Brugherio, Carugate, Barriera di Agrate",
    "A Sinistra Troviamo Lecco e Usmate Velate",
    "Poi Bivio per A4 Direzione Torino/Venezia",
    "Prendiamo A4 direzione Venezia",
    "USCITE: Agrate, TEM (Tangenziale Esterna Milanese), Cavenago/Cambiago, Trezzo sull'Adda, Capriate San Gervaso, Dalmine, Bergamo",
    "Usciamo a Bergamo",
    "Prendiamo direzione Orio Aereoporto"
  ]
}
    ]
}